### ISSUE TITLE
Package on pypi should link to repository

### ISSUE THREAD

**Issue by dwt** [plone/plone.session#19]
Currently, it lists the pypi page as its homepage. This could be kept as is, but then the repository should be listed as well. I think it would make more sense to link the repository as the homepage though.

If wanted, linking the documentation would be good too.

This can be achieved by adding a `project_urls` key to setup.py. See [here](https://github.com/dwt/fluent/blob/master/setup.py) for an example.

**Comment by jensens** [comment]
fixed as pointing url to github
