### ISSUE TITLE
Cookie attribute SameSite not set

### ISSUE THREAD

**Issue by reinhardt** [plone/plone.session#29]
The SameSite cookie attribute is not set on the login cookie.

**Comment by reinhardt** [comment]
See https://www.netsparker.com/blog/web-security/same-site-cookie-attribute-prevent-cross-site-request-forgery/

**Comment by ale-rt** [comment]
CC @plone/security-team

**Comment by ale-rt** [comment]
See also https://community.plone.org/t/same-site-cookie/12680
